language: java
os: windowsxp
jdk: oraclejdk8

  matrix:
  - SELENIUM_PLATFORM=WINDOWS SELENIUM_BROWSER=IE SELENIUM_VERSION=9

addons:
  firefox: "39.0"
    apt:
    packages:
        - oracle-java8-installer
  sauce_connect:
    username: "fernandogabane"
    access_key: "278srjfl2G"

before_script:
  - gem install selenium-webdriver
  
script: ant main
